name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: swift test -v --parallel --filter XnTemplateTests

  performance-tests:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - name: Run performance tests
        run: swift test -v --filter XnTemplatePerformance -Xswiftc -O
